language: ruby
rvm:
  - jruby-19mode
notifications:
  slack:
    secure: cWN5kMT5DZYHe3000OvD2uE6nUPMgfHcQwdjPtwhHYrjnf5UoSAWMBzEPcwGW98o6zWEcbt6frEV7tAmHRyisIQ2QVFmVAJoGett0HkIuD4oY6+Ys2SvQ1C2Bn7ueYVV9vIGFSmU2Gz3PFOEZkYtNF6KzYsAwW1gxC8KjTLYI98ia56cAGGLHkTX+rMMY4E4v+ZO/DFanInFgi6CP7j3e0HemwR8qK33Ud3IYxXomZ389icKokeuDjt/iUPCoStjYpGUkwUrGHff3UyvthtOa9J+Pab08ZY+NVx9Sm+s/s2a6+F6Kr8En4SW5UU0Fh6j8iJxPGo4lrHb2ulOFIRn4lSDomvrprl/sVREArDowTsNOfKibH08E7XEe3ud2Ypv/t2cgZU74KpFzbOVCqugPNg5LT63E6GKxXxkfIraiw6Zft8mPUpzuTXU69f+fPdIy5nEfESLheskevz7vfovvzHcxCKqOcSMz41xv/7dFM8M+1FArxpQgRZWdEBlylqTwMnE/I/0dz8D0dVuAI2yNOHfyc7IkJtARBIIV7VHW69kzXWutGN9jyM04VFL02QCRs3mxB0x4JsL5Yv36C8ewSXF43jx/F6F2OyQUsbZSgbRyJDAdvZZyN7ZY9rOOiMi2H7qCLYUe55cJGkY3am9hfQsmLvRSx6OeiPbgxZ/wdM=
