language: ruby

addons:
  code_climate:
    repo_token:
      secure: "EF0G+P1XuE0QYCn7Ez9rX4FXQGJPExRpxYpgD2RqnColikRP1YEeeMWEvQkzHwDLNAR4KdRvcC1rD7Xgr/cWQrs73sTfRb9mpQgE2DuY3XaaONBc+U3oe+y+0WAGdztWlA66sRZvABbESVLTd5mBVm2ydio0to8e5ZVY51SSi8AwtazAe9DVDFJvcWahXeicJ+2sBQcngS1OrOooQOkYliNV9R82DeAOmrbnQsto6V9HxtOJ2A8C8QXC2glOLCaE1qixbKe1/niDgW5VLz/Ns3kjgK3GB7b82qqB5CdDgy8/u/1iCFSmCuN8Wgl4D/z0gkLt8cCk3Rex3kjYwruSdmbvZBqKz/vFOa3xX89u1/PsKb+ABzQonKA3SecCe7gPtGGNQsqFz/lcXWGfnihpRQeEOvcX4njhWnXEJvESgxX58RAXqwnGKTMY2vqlQNsXNAr+1hb9J5y+rVero9kTZFe588rEUD74xnOyRonoh+Ig2QvwGz7792EB+FpqKOSL6LMCIjYhtqLJCmvpvf3yoLN9XW2ohEStoEap5A3DBJUpN1ABz5X5aogRD470oFIpc4Mz76yboFEj8zLzpIC99z5A/iZMNx72bW6juD2p7Swp0rqdIhoM7+/nfLkT4SuUyBmgJu8FF7sxyONLrYDRm9IPrZTctf2jAJGxkPArG0A="

jdk: oraclejdk8

rvm:
  - jruby-9.0.5.0

before_install:
  - |
    # Currently, Travis can't treat jruby 9.0.5.0
    ruby -v
    rvm get head
    rvm use jruby-9.0.5.0 --install
    ruby -v
    gem i bundler

script: bundle exec rake cov

gemfile:
  - gemfiles/embulk-0.8.0-latest
  - gemfiles/embulk-0.8.7
  - gemfiles/embulk-0.8.8
  - gemfiles/embulk-0.8.9
  - gemfiles/embulk-latest

matrix:
  exclude:
    - jdk: oraclejdk8 # Ignore all matrix at first, use `include` to allow build
  include:
    - {rvm: jruby-9.0.0.0, gemfile: gemfiles/embulk-0.8.0-latest}
    - {rvm: jruby-9.0.0.0, gemfile: gemfiles/embulk-0.8.7}
    - {rvm: jruby-9.0.0.0, gemfile: gemfiles/embulk-0.8.8}
    - {rvm: jruby-9.0.0.0, gemfile: gemfiles/embulk-0.8.9}
    - {rvm: jruby-9.0.0.0, gemfile: gemfiles/embulk-latest}
    

  allow_failures:
    # Ignore failure for *-latest
    - gemfile: embulk-0.8.0-latest
    - gemfile: embulk-latest
    
