language: ruby
rvm:
  - jruby-19mode
addons:
  code_climate:
    repo_token:
      secure: "EF0G+P1XuE0QYCn7Ez9rX4FXQGJPExRpxYpgD2RqnColikRP1YEeeMWEvQkzHwDLNAR4KdRvcC1rD7Xgr/cWQrs73sTfRb9mpQgE2DuY3XaaONBc+U3oe+y+0WAGdztWlA66sRZvABbESVLTd5mBVm2ydio0to8e5ZVY51SSi8AwtazAe9DVDFJvcWahXeicJ+2sBQcngS1OrOooQOkYliNV9R82DeAOmrbnQsto6V9HxtOJ2A8C8QXC2glOLCaE1qixbKe1/niDgW5VLz/Ns3kjgK3GB7b82qqB5CdDgy8/u/1iCFSmCuN8Wgl4D/z0gkLt8cCk3Rex3kjYwruSdmbvZBqKz/vFOa3xX89u1/PsKb+ABzQonKA3SecCe7gPtGGNQsqFz/lcXWGfnihpRQeEOvcX4njhWnXEJvESgxX58RAXqwnGKTMY2vqlQNsXNAr+1hb9J5y+rVero9kTZFe588rEUD74xnOyRonoh+Ig2QvwGz7792EB+FpqKOSL6LMCIjYhtqLJCmvpvf3yoLN9XW2ohEStoEap5A3DBJUpN1ABz5X5aogRD470oFIpc4Mz76yboFEj8zLzpIC99z5A/iZMNx72bW6juD2p7Swp0rqdIhoM7+/nfLkT4SuUyBmgJu8FF7sxyONLrYDRm9IPrZTctf2jAJGxkPArG0A="
notifications:
  slack:
    secure: cWN5kMT5DZYHe3000OvD2uE6nUPMgfHcQwdjPtwhHYrjnf5UoSAWMBzEPcwGW98o6zWEcbt6frEV7tAmHRyisIQ2QVFmVAJoGett0HkIuD4oY6+Ys2SvQ1C2Bn7ueYVV9vIGFSmU2Gz3PFOEZkYtNF6KzYsAwW1gxC8KjTLYI98ia56cAGGLHkTX+rMMY4E4v+ZO/DFanInFgi6CP7j3e0HemwR8qK33Ud3IYxXomZ389icKokeuDjt/iUPCoStjYpGUkwUrGHff3UyvthtOa9J+Pab08ZY+NVx9Sm+s/s2a6+F6Kr8En4SW5UU0Fh6j8iJxPGo4lrHb2ulOFIRn4lSDomvrprl/sVREArDowTsNOfKibH08E7XEe3ud2Ypv/t2cgZU74KpFzbOVCqugPNg5LT63E6GKxXxkfIraiw6Zft8mPUpzuTXU69f+fPdIy5nEfESLheskevz7vfovvzHcxCKqOcSMz41xv/7dFM8M+1FArxpQgRZWdEBlylqTwMnE/I/0dz8D0dVuAI2yNOHfyc7IkJtARBIIV7VHW69kzXWutGN9jyM04VFL02QCRs3mxB0x4JsL5Yv36C8ewSXF43jx/F6F2OyQUsbZSgbRyJDAdvZZyN7ZY9rOOiMi2H7qCLYUe55cJGkY3am9hfQsmLvRSx6OeiPbgxZ/wdM=
jdk:
  - oraclejdk8
gemfile:
  - gemfiles/embulk-0.6.13
  - gemfiles/embulk-0.6.14
  - gemfiles/embulk-0.6.15
  - gemfiles/embulk-0.6.16
  - gemfiles/embulk-0.6.17
  - gemfiles/embulk-0.6.18
  - gemfiles/embulk-0.6.19
  - gemfiles/embulk-0.6.20
  - gemfiles/embulk-0.6.21
  - gemfiles/embulk-0.6.22
  - gemfiles/embulk-0.6.23
  - gemfiles/embulk-0.6.24
  - gemfiles/embulk-0.6.25
  - gemfiles/embulk-latest

matrix:
  allow_failures:
    - gemfile: gemfiles/embulk-0.6.22
    - gemfile: gemfiles/embulk-latest
