language: ruby
rvm:
  - jruby-19mode
notifications:
  slack:
    secure: QouVFiuH4dTRpjUExfu4NqOYCmt53rmchedTbXqsDXOuLoUbGCMHJgoaYnxJn4Gltqydp8dHXJTE+1hBHZTCGqvO4gng5Z66N7r2DaUk15+mCJPcRl15aMX6J5bXvMp5M7xZYd4AhmB4b3RsdsF4qyH1rf2k9IhakQX09xj1C1OjO3SvMDT/PSQ3cV4mVs4zltYBmNeln9J5rZNexHBg/Mbwz1IqPnR0In5vEUhwBwRc3eo7JoxjBR5/3ffVJcLG1uf9askuW3YacR4XVMYXzFlUErS9QHyugSNTac03YpJmfg8YtY2H1o5ScicwMda3T0nKixHff/Ftkwh7DNsji0edW1WVk+Zt+0P/8ULj/k5gS4uhCERaXNFqRovwqI7is2I1rQFs3TQAQynmXyT0y/jHF0YspTStvuUjSFvuX4P0yaeX39Flih8ZM/js+TkKWjunFsBueqLzcDIjaJ2DFRPi1xDkmwayBhZEpECUE5R19170QsOyIbiG4NFXWWbDIUIapFZKoiohIp46J+NqWYu0Hp/TN6wcqPW7bXVamMma28koM1BLVajW/Ikknqg3Yzf7pzKkRxmoda/fkdfMkr4pqH056YIVKeHKRbrHnfEBArG++HW/T+L8GBW8wH+9fJVeu0G1VsSFH57YARIyO3WF0eqpHB6HHySn2p+DM3Y=
